import { mediaAssets } from "./mediaAssets";

export const dealerConfig = {
  id: "level-up-demo",
  demoMode: true,
  siteURL: "",
  verifiedDealerData: false,
  name: "Level Up Auto Sales",
  shortName: "LEVEL UP",
  tagline: "Your next chapter. Your next drive.",
  heroTitle: "LEVEL UP YOUR DRIVE.",
  heroSubtitle: "Luxury. Performance. Everyday possibilities.",
  logo: {
    asset: mediaAssets.brand,
    wordmark: "LEVEL UP",
    subtitle: "AUTO SALES",
    // The supplied brand is within a wider scene. Frame it without altering its pixels.
    crop: {
      left: 32.7,
      top: 16.4,
      width: 32.7,
      height: 20.1,
      sourceAspect: 1672 / 941,
    },
  },
  contact: {
    phone: "(973) 688-8095",
    sms: "",
    email: "",
    address: "604 Broadway",
    city: "Newark",
    state: "NJ",
    zip: "07104",
    hours: ["Hours awaiting dealer confirmation — call before visiting"],
    directionsURL: "https://goo.gl/maps/K4DyrRSYqbZj4X4j9?coh=178572&entry=tt",
    map: {
      query: "604 Broadway, Newark, NJ 07104",
      coordinates: null as { latitude: number; longitude: number } | null,
      zoom: 14,
      locationVerified: true,
    },
  },
  socialLinks: [] as { label: string; url: string }[],
  financing: {
    mode: "built-in" as "built-in" | "external",
    providerURL: "",
    defaultAPR: 7.9,
    defaultTerm: 72,
    demo: true,
  },
  trade: { enabled: true, demo: true },
  leads: { mode: "demo" as "demo" | "api", endpoint: "" },
  reviews: { source: "Sample stories", demo: true },
  intro: {
    enabled: true,
    videoURL: mediaAssets.video,
    videoAvailable: true,
    playbackRate: 3.1,
    durationMs: 4800,
    poster: mediaAssets.doorsOpen,
    scenes: {
      doorsOpen: mediaAssets.doorsOpen,
      doorsClosed: mediaAssets.doorsClosed,
      burnout: mediaAssets.burnout,
      smoke: mediaAssets.smoke,
    },
    version: "supplied-cinematic-v1",
  },
  theme: {
    background: "#0c0f10",
    surface: "#f3f2ed",
    accent: "#b9a273",
    primaryBackground: mediaAssets.blackMarble,
    surfaceBackground: mediaAssets.whiteMarble,
    backgroundOverlay: 0.75,
    surfaceOverlay: 0.88,
  },
  cta: {
    inventory: "Shop inventory",
    financing: "Get approved",
    trade: "Value your trade",
  },
  about: {
    heading: "MORE THAN A DEALERSHIP.",
    copy: "A considered collection. A more personal way to shop. From the first look to the next chapter, discover a dealership experience designed around you.",
    trust: [
      "Curated inventory",
      "Flexible financing",
      "Trade-ins welcome",
      "A personal experience",
    ],
  },
  legal: {
    demo: "Concept dealership demo. All vehicles, prices, reviews, and form submissions are sample content. No vehicle availability or financing offer is implied.",
    payment:
      "Estimates only. Actual APR, taxes, fees, down payment, loan availability and terms depend on lender approval and transaction details.",
    privacy:
      "Demo forms are processed only in this browser session and are not sent to a dealership. Use fictional information. Never enter SSNs or sensitive credit information.",
  },
};
