export const dealerConfig = {
  id: "level-up-demo",
  demoMode: true,
  siteURL: "",
  verifiedDealerData: false,
  name: "Level Up Auto Sales",
  shortName: "LEVEL UP",
  tagline: "Your next chapter. Your next drive.",
  heroTitle: "LEVEL UP YOUR DRIVE.",
  heroSubtitle: "Luxury. Performance. Everyday possibilities.",
  logo: { asset: "", mark: "◇", wordmark: "LEVEL UP", subtitle: "AUTO SALES" },
  contact: {
    phone: "",
    sms: "",
    email: "",
    address: "Dealer address awaiting verification",
    city: "",
    state: "",
    zip: "",
    hours: ["Demo showroom · hours to be confirmed"],
    directionsURL: "",
  },
  socialLinks: [] as { label: string; url: string }[],
  financing: {
    mode: "built-in" as "built-in" | "external",
    providerURL: "",
    defaultAPR: 7.9,
    defaultTerm: 72,
    demo: true,
  },
  trade: { enabled: true, demo: true },
  leads: { mode: "demo" as "demo" | "api", endpoint: "" },
  reviews: { source: "Sample stories", demo: true },
  intro: {
    enabled: true,
    videoURL: "/cinematic-intro.mp4",
    videoAvailable: false,
    durationMs: 4400,
    poster: "/images/hero.jpg",
  },
  theme: { background: "#0c0f10", surface: "#f3f2ed", accent: "#b9a273" },
  cta: {
    inventory: "Shop inventory",
    financing: "Get approved",
    trade: "Value your trade",
  },
  about: {
    heading: "MORE THAN A DEALERSHIP.",
    copy: "A considered collection. A more personal way to shop. From the first look to the next chapter, discover a dealership experience designed around you.",
    trust: [
      "Curated inventory",
      "Flexible financing",
      "Trade-ins welcome",
      "A personal experience",
    ],
  },
  legal: {
    demo: "Concept dealership demo. All vehicles, prices, reviews, and form submissions are sample content. No vehicle availability or financing offer is implied.",
    payment:
      "Estimates only. Actual APR, taxes, fees, down payment, loan availability and terms depend on lender approval and transaction details.",
    privacy:
      "Demo forms are processed only in this browser session and are not sent to a dealership. Use fictional information. Never enter SSNs or sensitive credit information.",
  },
};
